name: Test

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: |
            "$HOME/.gradle/caches/"
            "$HOME/.gradle/wrapper/"
            "$HOME/.android/build-cache"
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Install Ruby
        uses: ruby/setup-ruby@v1.52.0
        with:
          ruby-version: 2.6.3
          bundler-cache: true
      - name: Fastlane
        run: FASTLANE_SKIP_UPDATE_CHECK=1 bundle exec fastlane test
      - name: Clean up
        run: |
          rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
          rm -fr $HOME/.gradle/caches/*/plugin-resolution/
